// Public intake guidance only; no customer documents, rates or route guarantees.
export const enquiryGuidance: Record<string, { title: string; intro: string; items: string[] }> = {
  'air-freight': { title: 'Preparing an air-freight enquiry', intro: 'Package dimensions and the cargo-ready date help define the available options.', items: ['Origin and destination, including pickup or delivery needs', 'Commodity, package count, outer dimensions and gross weight', 'Ready date and any required arrival date', 'Any batteries, liquids or other special handling requirements'] },
  'ocean-freight': { title: 'Preparing an ocean-freight enquiry', intro: 'Confirm the international and Nepal-side stages as part of the same discussion.', items: ['Origin, final destination and commodity', 'Container requirement, or package sizes and total weight for consolidated cargo', 'Ready date and available packing details', 'Agreed responsibilities at origin, transit and destination'] },
  'cross-border': { title: 'Preparing a cross-border enquiry', intro: 'Route and border arrangements depend on the individual shipment.', items: ['Pickup and final delivery locations', 'Cargo description, packaging, dimensions and weight', 'Available commercial and transport documents', 'Receiving arrangements and access restrictions'] },
  'customs-clearance': { title: 'Preparing a customs enquiry', intro: 'Share the cargo description and available documentation so the required scope can be reviewed.', items: ['Commodity description and available commercial documents', 'Transport mode and expected arrival point', 'Shipment origin and final destination', 'The customs and delivery stages you need KCPL to coordinate'] },
  'project-cargo': { title: 'Plan around each piece', intro: 'Start with individual cargo details, route access and the final delivery site.', items: ['Piece-by-piece dimensions and gross weights', 'Available drawings, packing details and handling instructions', 'Delivery-site entrance, access constraints and receiving arrangements', 'Unloading and positioning scope, including who is responsible'] },
  'ground-transport': { title: 'Preparing an inland movement', intro: 'The delivery location matters as much as the collection point.', items: ['Collection point and full delivery location', 'Commodity, package dimensions and weight', 'Access restrictions and receiving hours', 'Loading and unloading arrangements'] },
  'door-to-door': { title: 'Define the pickup-to-delivery scope', intro: 'Clear responsibilities help the freight, customs and local stages fit together.', items: ['Pickup and final delivery locations', 'Cargo, dimensions, weight and ready date', 'Available commercial and shipping documents', 'Responsibilities already agreed with other operating parties'] },
  warehousing: { title: 'Discuss the storage requirement', intro: 'Location, availability and handling scope need to be confirmed for your enquiry.', items: ['Required location and storage duration', 'Cargo type, package count, dimensions and weight', 'Any storage or handling conditions', 'Expected release dates and distribution destinations'] },
  'partner-enquiry': { title: 'Define the Nepal-side handover', intro: 'Tell us which stages you need KCPL to coordinate.', items: ['Arrival gateway and final delivery location', 'Cargo description, weights, dimensions and available documents', 'Responsibilities at origin, transit and destination', 'Local handling requirements and project-site constraints'] },
};
