export const services = [
  { id: 'air-freight', number: '01', title: 'Air freight', short: 'International air imports and exports, from cargo preparation to onward delivery.', detail: 'Air imports from overseas origins to Tribhuvan International Airport (TIA), Kathmandu, alongside air export coordination. Shipping documents, customs requirements and onward delivery arrangements are considered as part of the movement.', scope: ['Air imports to TIA, Nepal', 'Export and overseas-agent coordination', 'Air waybill, customs and destination handovers'], note: 'Share the cargo-ready date, package dimensions and total weight so the available options can be assessed.' },
  { id: 'ocean-freight', number: '02', title: 'Ocean freight', short: 'Containers and breakbulk via regional seaports, with onward movement to Nepal.', detail: 'Container bookings from international origins to Nepal via Visakhapatnam (Vizag) and Kolkata ports. KCPL also coordinates breakbulk vessel bookings for cargo moving from overseas origins through a suitable seaport and onward to landlocked Nepal.', scope: ['Full-container and consolidated cargo (FCL / LCL)', 'Breakbulk vessel booking', 'Port, transit documentation and onward movement to Nepal'], note: 'Port selection, vessel availability and onward routing depend on the cargo, origin, delivery location and current operating conditions.' },
  { id: 'cross-border', number: '03', title: 'Road & cross-border freight', short: 'Nepal–India freight and China–Nepal coordination, with border requirements built in.', detail: 'Project and trading cargo pickup from Indian factories for delivery into Nepal, with the customs crossing selected around the shipment. KCPL also coordinates China–Nepal cargo movements with the relevant origin and border operating parties.', scope: ['Indian factory pickup and Nepal-side delivery', 'China–Nepal logistics coordination', 'Customs-crossing selection and border documentation'], note: 'The appropriate customs point, route and availability are confirmed for each shipment; this is not a scheduled service through every crossing.' },
  { id: 'customs-clearance', number: '04', title: 'Customs clearance', short: 'Documents, release requirements and transport handovers coordinated together.', detail: 'Customs and document coordination for international cargo, aligned with the selected air, ocean, road or rail movement and the requirements for release in Nepal.', scope: ['Commercial and shipping document review', 'Customs process coordination', 'Release and transport handovers'], note: 'Send the commodity description and available commercial documents early so requirements can be checked.' },
  { id: 'project-cargo', number: '05', title: 'Project cargo', short: 'Heavy, oversized and sensitive equipment planned around the cargo and the route.', detail: 'Project cargo, heavy transformers and equipment pickup from China and India to Nepal. Planning considers piece weight, handling requirements, vehicle selection, border coordination, route access and the final delivery site.', scope: ['Heavy transformer and equipment pickup', 'Weight, dimensions, route and access planning', 'Handling and site-delivery coordination'], note: 'Provide individual piece weights, dimensions and available drawings, together with site-access and unloading details.' },
  { id: 'ground-transport', number: '06', title: 'Ground transport', short: 'Inland movement linked to the wider shipment plan.', detail: 'Inland transport arrangements between the arrival gateway, customs point and final destination, with suitable vehicles and delivery requirements considered before dispatch.', scope: ['Nepal-side inland transport', 'Vehicle and delivery coordination', 'Customs-to-destination handover'], note: 'Tell us about restricted access, receiving hours and any handling arrangements at the delivery point.' },
  { id: 'door-to-door', number: '07', title: 'Door-to-door coordination', short: 'Pickup, freight, customs and delivery connected through an agreed scope.', detail: 'Pickup-to-delivery coordination through the required freight and customs stages. Responsibilities at origin and destination are agreed with the shipper and the relevant overseas counterparts.', scope: ['Pickup and origin coordination', 'International freight and customs stages', 'Destination delivery arrangements'], note: 'The quotation should define the agreed scope, responsibilities and any excluded charges.' },
  { id: 'warehousing', number: '08', title: 'Warehousing & distribution', short: 'Warehouse facilities in India and Nepal, linked with freight and delivery.', detail: 'Warehouse facilities at Raxaul in India and Birgunj, Nepalgunj, Surkhet, Chovar and Thimi in Nepal support storage and onward-movement requirements. Availability, handling needs and the scope of support are confirmed for each enquiry.', scope: ['Storage in India and Nepal', 'Handling and release coordination', 'Distribution planning enquiries'], note: 'Specify the location, storage duration and any special conditions. Capacity and suitability must be confirmed; no temperature-controlled or bonded-storage capability is implied.' },
];
export const processSteps = [
  { title: 'Define the cargo', text: 'Share the origin, destination, commodity, weight, dimensions and ready date.' },
  { title: 'Agree the scope', text: 'Confirm the freight stages, responsibilities, documentation and handling needs.' },
  { title: 'Coordinate movement', text: 'Align transport, customs and the handovers between operating counterparts.' },
  { title: 'Arrange delivery', text: 'Coordinate release, inland movement and the receiving arrangements.' },
];
