export const services = [
  { id: 'air-freight', number: '01', title: 'Air freight', short: 'International air imports and exports, from cargo preparation to onward delivery.', detail: 'Air import and export coordination with overseas counterparts, including shipping documents, customs requirements and onward delivery arrangements.', scope: ['Import and export coordination', 'Air waybill and document coordination', 'Customs and destination handovers'], note: 'Share the cargo-ready date, package dimensions and total weight so the available options can be assessed.' },
  { id: 'ocean-freight', number: '02', title: 'Ocean freight', short: 'Container and consolidated cargo through regional gateways into Nepal.', detail: 'Full-container and less-than-container-load movements coordinated through suitable regional ports, with transit documentation and onward movement into Nepal considered together.', scope: ['FCL and LCL coordination', 'Origin and destination-agent liaison', 'Port, transit and Nepal-side arrangements'], note: 'Port selection and onward routing depend on the cargo, origin, delivery location and current operating conditions.' },
  { id: 'cross-border', number: '03', title: 'Road & cross-border freight', short: 'Nepal–India freight and China–Nepal coordination, with border requirements built in.', detail: 'Regional road and cross-border movements aligned with documentation, customs and inland delivery requirements. KCPL coordinates Nepal–India freight and China–Nepal cargo movements with the relevant operating counterparts.', scope: ['Nepal–India road movements', 'China–Nepal logistics coordination', 'Border documentation and onward delivery'], note: 'The route and border arrangements are assessed for each shipment; availability is confirmed when planning the movement.' },
  { id: 'customs-clearance', number: '04', title: 'Customs clearance', short: 'Documents, release requirements and transport handovers coordinated together.', detail: 'Customs and document coordination for international cargo, aligned with the selected air, ocean, road or rail movement and the requirements for release in Nepal.', scope: ['Commercial and shipping document review', 'Customs process coordination', 'Release and transport handovers'], note: 'Send the commodity description and available commercial documents early so requirements can be checked.' },
  { id: 'project-cargo', number: '05', title: 'Project cargo', short: 'Heavy, oversized and sensitive equipment planned around the cargo and the route.', detail: 'Additional planning for heavy transformers, oversized pieces and sensitive electrical equipment, with attention to handling, vehicle selection, route access and the delivery site.', scope: ['Weight and dimension assessment', 'Route and access planning', 'Handling and site-delivery coordination'], note: 'Provide individual piece weights, dimensions and available drawings, together with site-access and unloading details.' },
  { id: 'ground-transport', number: '06', title: 'Ground transport', short: 'Inland movement linked to the wider shipment plan.', detail: 'Inland transport arrangements between the arrival gateway, customs point and final destination, with suitable vehicles and delivery requirements considered before dispatch.', scope: ['Nepal-side inland transport', 'Vehicle and delivery coordination', 'Customs-to-destination handover'], note: 'Tell us about restricted access, receiving hours and any handling arrangements at the delivery point.' },
  { id: 'door-to-door', number: '07', title: 'Door-to-door coordination', short: 'Pickup, freight, customs and delivery connected through an agreed scope.', detail: 'Pickup-to-delivery coordination through the required freight and customs stages. Responsibilities at origin and destination are agreed with the shipper and the relevant overseas counterparts.', scope: ['Pickup and origin coordination', 'International freight and customs stages', 'Destination delivery arrangements'], note: 'The quotation should define the agreed scope, responsibilities and any excluded charges.' },
  { id: 'warehousing', number: '08', title: 'Warehousing & distribution', short: 'Discuss storage and distribution needs as part of your shipment.', detail: 'Storage and distribution support can be discussed alongside freight and delivery requirements. Location, availability, handling needs and the scope of support are confirmed for the individual enquiry.', scope: ['Storage requirement assessment', 'Handling and release coordination', 'Distribution planning enquiries'], note: 'Please specify the location, storage duration and any special conditions required for your cargo.' },
];
export const processSteps = [
  { title: 'Define the cargo', text: 'Share the origin, destination, commodity, weight, dimensions and ready date.' },
  { title: 'Agree the scope', text: 'Confirm the freight stages, responsibilities, documentation and handling needs.' },
  { title: 'Coordinate movement', text: 'Align transport, customs and the handovers between operating counterparts.' },
  { title: 'Arrange delivery', text: 'Coordinate release, inland movement and the receiving arrangements.' },
];
