'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { statuses } from '@/lib/enquiry-validation';
import { services } from '@/content/services';
type Item = { id: string; reference: string; data: string; status: string; version: number; created_at: string; updated_at: string };
type Detail = { item: Item; files: { id: string; name: string; size: number }[]; events: { actor: string; message: string; created_at: string }[] };
function date(value: string) { return new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kathmandu' }).format(new Date(value)) + ' NPT'; }
function label(value: string) { return value.replaceAll('-', ' '); }
async function api<T = { saved: boolean }>(url: string, options?: RequestInit) { const response = await fetch(url, { cache: 'no-store', ...options }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? 'Request unavailable.'); return data; }
export function StaffDesk() {
  const [items, setItems] = useState<Item[]>([]); const [status, setStatus] = useState(''); const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [more, setMore] = useState(false);
  const [detail, setDetail] = useState<Detail | null>(null); const [selected, setSelected] = useState(''); const [note, setNote] = useState(''); const [nextStatus, setNextStatus] = useState('new');
  const [error, setError] = useState(''); const [detailError, setDetailError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0); const [notice, setNotice] = useState('');
  useEffect(() => { const controller = new AbortController(); api<{items: Item[]; hasMore: boolean}>(`/api/staff/enquiries?status=${encodeURIComponent(status)}&q=${encodeURIComponent(search)}&page=${page}`, { signal: controller.signal }).then(data => { setItems(data.items); setMore(data.hasMore); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [status, search, page, revision]);
  useEffect(() => { if (!selected) return; const controller = new AbortController(); api<Detail>(`/api/staff/enquiries/${selected}`, { signal: controller.signal }).then(data => { setDetail(data); setNextStatus(data.item.status); }).catch(e => { if (!controller.signal.aborted) setDetailError(e.message); }); return () => controller.abort(); }, [selected]);
  async function save(event: FormEvent) { event.preventDefault(); if (!detail || busy) return; setBusy(true); setDetailError(''); setNotice(''); try { await api(`/api/staff/enquiries/${detail.item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: nextStatus, version: detail.item.version, note }) }); setNotice('Update saved.'); setNote(''); setDetail(await api<Detail>(`/api/staff/enquiries/${detail.item.id}`)); setRevision(v => v + 1); } catch (e) { setDetailError((e as Error).message); } finally { setBusy(false); } }
  const fields: Record<string,string> = detail ? JSON.parse(detail.item.data) : {};
  return <><form className="desk-filters" onSubmit={e => { e.preventDefault(); setLoading(true); setError(''); setSearch(query); setPage(0); setRevision(v => v + 1); }}><div className="form-field"><label htmlFor="desk-search">Search cargo, company or reference</label><input id="desk-search" value={query} onChange={e => setQuery(e.target.value)} maxLength={100} /></div><div className="form-field"><label htmlFor="desk-status">Enquiry status</label><select id="desk-status" value={status} onChange={e => { setLoading(true); setError(''); setStatus(e.target.value); setPage(0); }}><option value="">All enquiries</option>{statuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></div><button className="button" type="submit">Search</button><button className="button button-secondary" type="button" onClick={() => { setLoading(true); setError(''); setRevision(v => v + 1); }}>Refresh list</button></form>
  <div className="desk-workspace"><section aria-label="Enquiries" aria-busy={loading}><p role="status">{loading ? 'Loading enquiries…' : error || (items.length ? `Page ${page + 1} · ${items.length} enquiries` : 'No enquiries match these filters.')}</p>{!error && items.map(item => { const data = JSON.parse(item.data); return <button className={`desk-row ${selected === item.id ? 'is-selected' : ''}`} key={item.id} disabled={busy} onClick={() => { if (item.id === selected) return; if (note && !window.confirm('Discard the unsaved follow-up note?')) return; setDetail(null); setDetailError(''); setNote(''); setNotice(''); setSelected(item.id); }} aria-pressed={selected === item.id}><span className="small muted">{date(item.created_at)} · {label(item.status)}</span><strong>{data.Origin} → {data.Destination}</strong><span>{data.Company || data.Name} · {services.find(s => s.id === data['Service required'])?.title ?? label(data['Service required'])}</span><span className="small desk-reference">{item.reference}</span></button>; })}<div className="draft-actions"><button className="button button-secondary" disabled={loading || page === 0} onClick={() => { setLoading(true); setPage(p => p - 1); }}>Previous</button><button className="button button-secondary" disabled={loading || !more} onClick={() => { setLoading(true); setPage(p => p + 1); }}>Next</button></div></section>
  <section className="desk-detail" aria-label="Selected enquiry"><p role="alert">{detailError}</p>{!detail ? <p>{selected && !detailError ? 'Loading enquiry…' : 'Select an enquiry to review cargo, documents and follow-up.'}</p> : <><p className="small desk-reference">{detail.item.reference}</p><h2>{fields.Company || fields.Name}</h2><a className="inline-link" href={`mailto:${fields.Email}?subject=${encodeURIComponent('Re: ' + detail.item.reference)}`}>Email {fields.Name}</a><dl className="desk-fields">{Object.entries(fields).filter(([,v]) => v).map(([key,value]) => <div key={key}><dt>{key}</dt><dd>{key === 'Service required' ? services.find(s => s.id === value)?.title ?? label(value) : value}</dd></div>)}</dl><button type="button" className="button button-secondary" disabled={busy} onClick={async () => { try { const fresh = await api<Detail>(`/api/staff/enquiries/${detail.item.id}`); setDetail(fresh); setNextStatus(fresh.item.status); setDetailError(''); } catch (e) { setDetailError((e as Error).message); } }}>Refresh enquiry</button><h3>Cargo documents</h3><p className="small muted">Customer-supplied files are not malware-scanned. Download only when needed; scan before opening.</p>{detail.files.length ? <ul>{detail.files.map(f => <li key={f.id}><a className="inline-link" href={`/api/staff/files/${f.id}`}>{f.name}</a> <span className="small">({Math.ceil(f.size / 1000)} KB)</span></li>)}</ul> : <p>No attachments supplied.</p>}<form onSubmit={save}><div className="form-field"><label htmlFor="follow-status">Status</label><select id="follow-status" value={nextStatus} onChange={e => setNextStatus(e.target.value)} disabled={busy}>{statuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></div><div className="form-field"><label htmlFor="follow-note">Internal follow-up note</label><textarea id="follow-note" rows={4} value={note} onChange={e => setNote(e.target.value)} maxLength={2000} disabled={busy} placeholder="Missing dimensions, agreed next step, or handover details" /></div><p className="small muted">Internal only. Saving does not send an email or confirm a booking.</p><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save follow-up'}</button></form><p role="status">{notice}</p><h3>Follow-up history</h3>{detail.events.length ? <ol className="desk-history">{detail.events.map((event,i) => <li key={i}><time className="small muted">{date(event.created_at)}</time><p>{event.message}</p><span className="small muted">Recorded by authorised staff</span></li>)}</ol> : <p>No follow-up recorded yet.</p>}</>}</section></div></>;
}
