import { Container, PageIntro, Eyebrow } from '@/components/ui';
import { ResponsiveImage } from '@/components/responsive-image';
import { QuoteCTA } from '@/components/sections';
import { projects, planning } from '@/content/projects';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Project Cargo & Heavy Transport in Nepal', 'Heavy, oversized and sensitive cargo planning in Nepal: piece weight, dimensions, route access, customs and delivery-site coordination.', '/project-cargo');
export default function ProjectCargoPage() {
  return <><PageIntro dark label="Project cargo / Heavy · Oversized · Sensitive" title={<>When the route<br />becomes part<br />of the job.</>}><p>Heavy and oversized cargo requires more than transport capacity. It requires planning around the cargo, the route and the final delivery site.</p><p className="intro-small">Transformers. Electrical equipment. Cargo beyond standard handling.</p></PageIntro>
    <section className="project-image-band dark"><Container><ResponsiveImage image="industrial" className="wide-photo" priority caption="Industrial logistics context; not a photograph of a KCPL project." /><div className="technical-strip"><span>Origin</span><span>Border & customs</span><span>Inland route</span><span>Delivery site</span></div></Container></section>
    <section className="section"><Container><div className="section-heading"><Eyebrow number="01">Planning the movement</Eyebrow><h2>Three parts of one transport plan.</h2></div><div className="planning-list">{planning.map((p, i) => <article key={p.title}><span className="planning-number">0{i + 1}</span><div><h3>{p.title}</h3><p>{p.intro}</p></div><ul className="plain-list">{p.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></Container></section>
    <section className="project-records"><Container><div className="editorial-grid"><div><Eyebrow number="02">Company-reported experience</Eyebrow><h2>Power-sector cargo.<br />Practical constraints.</h2><p className="muted measure">Selected cargo-handling references from KCPL’s company material. These describe logistics roles associated with the projects.</p><p className="small muted measure">Project references do not imply that KCPL designed, built or commissioned the infrastructure.</p></div><div>{projects.map(p => <article className="project-record" key={p.place}><div className="record-heading"><h3>{p.place}</h3><span>{p.cargo}</span></div><dl><div><dt>KCPL’s role</dt><dd>{p.role}</dd></div><div><dt>Planning context</dt><dd>{p.consideration}</dd></div></dl></article>)}</div></div></Container></section>
    <section className="section"><Container className="editorial-grid"><div><Eyebrow number="03">Sensitive equipment</Eyebrow><h2>Handling matters<br />all the way to site.</h2></div><div><p className="service-lead">Electrical and GIS equipment can bring additional packing, restraint and movement requirements. Those conditions belong in the transport discussion from the start.</p><p className="muted">Agree the cargo condition, available handling instructions, vehicle requirements, unloading scope and responsibilities with the relevant parties before movement.</p></div></Container></section><QuoteCTA project /></>;
}
